--1

UPDATE EMPLEADOS
SET DEP_NO=(SELECT D.DEP_NO 
FROM DEPARTAMENTOS D 
WHERE D.LOCALIDAD='MADRID')
WHERE DEP_NO IN(SELECT DE.DEP_NO 
FROM DEPARTAMENTOS DE 
WHERE DE.LOCALIDAD='BARCELONA' OR DE.LOCALIDAD='SEVILLA');

--2

UPDATE CLIENTES C
SET DEBE=(SELECT SUM(P.UNIDADES*PR.PRECIO_ACTUAL) FROM PEDIDOS P JOIN PRODUCTOS PR
ON P.PRODUCTO_NO=PR.PRODUCTO_NO
WHERE P.PRODUCTO_NO=PR.PRODUCTO_NO AND P.CLIENTE_NO=C.CLIENTE_NO);


